stack: wayner/brucer

version: 0.1.0


services:
  web:
    image: waybarrios/test_nginx
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=80
      - KONTENA_LB_VIRTUAL_HOSTS=brucer.cientifi.co
    links:
      - internet_lb
    deploy:
      strategy: ha
      wait_for_port: 80

affinity:
  - node==wild-bush-72 